Restorant menu
OleksiiFedorenko/goit-team-project-01 pull request #9
Opened 2022-12-02 13:32 UTC by chemvic

2022-12-04 16:26 UTC, teti-ruzh requested changes

2022-12-05 00:32 UTC, opanchen commented
Переверстав позиціонування таблиць флексами, щоб прибрати зайві марджини. 
Додав колір фону.
Виправив деякі синтаксичні помилки в коді. 

Вважаю, що на даному етапі можна мерджити в мейн. Додатковий рефактиринг коду та/або баг-фікс за бажанням учасників чи на вимогу ментора. 

Також зверну увагу, що до першого брейк-поінту  (< 414px) ломається структура внутрішніх елементів таблиць, і викривляється пропорційність їх розташування. Необхідно буде правити, але поки не маю рішення. 

Розмітку декоративних  вертикальних ліній залшаю без змін. У разі потреби, виконаєте баг-фікс.

2022-12-05 00:34 UTC, OleksiiFedorenko approved these changes

2022-12-05 01:16 UTC, OleksiiFedorenko approved these changes

2022-12-05 01:16 UTC, merged